version: '3.1'
services:

  acquirer-backend:
    build:
      context: .
      dockerfile: Dockerfile-acquirer-backend
    command: ["./scripts/wait-for-mysql.sh", "npm", "run", "acquirer-backend:start"]
    ports:
      - "5555:5555"
    environment:
      - HOST=0.0.0.0
      - PORT=5555
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=merchant_acquirer_db
    depends_on:
      - db

  acquirer-frontend:
    build:
      context: .
      dockerfile: Dockerfile-acquirer-frontend
    ports:
      - "5172:5172"

  # TODO: To do this
  # registry-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-registry-backend

  db:
    image: mysql:8.0.33

    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=merchant_acquirer_db
    ports:
      - 3306:3306
